### ISSUE TITLE
Using MockBehavior.Strict

### ISSUE THREAD

**Issue by Lapov** [scott-xu/EntityFramework.Testing#20]
Hi guys! 
I tried to make a mock for my simple DbContext and It works fine For MockBehavior.Default, But when I try to use MockBehavior.Strict I cannot even get an Object of this mock.

I made some workaround for one exception using additional Setup for Set<> method:
```
_myContextMock.Setup(x => x.MyEntities).Returns(mockSetObject);
_myContextMock.Setup(x => x.Set<MyEntity>()).Returns(mockSetObject);
```

but now got:

```
System.Reflection.TargetInvocationException : Exception has been thrown by the target of an invocation.
  ----> Moq.MockException : IEnumerable.GetEnumerator() invocation failed with mock behavior Strict.
All invocations on the mock must have a corresponding setup.
```
And it is when I try to get an Object of my Mock, I mean when I use _myContextMock.Object

**Comment by scott-xu** [comment]
The exception message has already self explained.

**Comment by Lapov** [comment]
Super fast and super informative

**Comment by scott-xu** [comment]
Didn't you agree the error message has already explained? You have to setup all invocations with mock behavior strict. 

Moq.MockException : IEnumerable.GetEnumerator() invocation failed with mock behavior Strict.
All invocations on the mock must have a corresponding setup.

I could not reply because it's not the issue of this project.

Anyway, sorry for the late.

**Comment by Lapov** [comment]
@scott-xu Thank you very much for your extension. It is useful to use it(setup context data in 1 line) with default mock behavior. But it does not work with Mock behavior strict.

In your code there is a row: 
`mock.As<IQueryable<TEntity>>().Setup(m => m.GetEnumerator()).Returns(query.GetEnumerator);`
so, why Do I need to make an additional setup for GetEnumerator?

And I tried to make a explicit setup for GetEnumerator() it did not help. It returns:
```
System.Reflection.TargetInvocationException : Exception has been thrown by the target of an invocation.
  ----> Moq.MockException : DbContext.MyEntities= [MyEntity, MyEntity, MyEntity, MyEntity] invocation failed with mock behavior Strict.
```
With stack trace:

```
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeConstructorInfo.Invoke(BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.RuntimeType.CreateInstanceImpl(BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes, StackCrawlMark& stackMark)
   at System.Activator.CreateInstance(Type type, BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes)
   at System.Activator.CreateInstance(Type type, Object[] args)
   at Castle.DynamicProxy.ProxyGenerator.CreateClassProxyInstance(Type proxyType, List`1 proxyArguments, Type classToProxy, Object[] constructorArguments)
   at Moq.Proxy.CastleProxyFactory.CreateProxy(Type mockType, ICallInterceptor interceptor, Type[] interfaces, Object[] arguments)
   at Moq.Mock`1.<InitializeInstance>b__24_0()
   at Moq.PexProtector.Invoke(Action action)
   at Moq.Mock`1.InitializeInstance()
   at Moq.Mock`1.OnGetObject()
   at Moq.Mock.GetObject()
   at Moq.Mock.get_Object()
   at Moq.Mock`1.get_Object()
```

The last exception is not so informative and I do not understand what am I doing wrong =(
